spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb  
    username: root                           
    password: password                       
    driver-class-name: com.mysql.cj.jdbc.Driver  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  
    show-sql: true
  # Configuración del servidor
  server:
    port: 8081  # Puerto específico para authservice, puede cambiarse según necesidades
  sql:
    init:
      mode: never 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Configuración del JWT
jwt:
  secret: mySecretKey
  expiration: 3600000  # Expiración del token en milisegundos
